<?php
include_once 'common_functions.php';
include_once 'ClassStaff.php';
include_once 'assets/fpdf/fpdf.php';
include_once 'database_credentials.php';
include_once 'course-class.php';



$session = new SessionManager();



$dbconn = new mysqli(DB_HOST, DB_USER, DB_PASS, DB_NAME);
if($dbconn->connect_error) {
		die("Database connection error: " . $dbconn->connect_error);
}


class PDF extends FPDF {
	function Footer(){
		$this->SetY(-15);
		$this->SetFont('Arial','',7);
		$this->Cell(0 ,5,'Note : This is a computer generated sheet, no signature is required.',1,1,'C');
		$this->SetFont('Arial','',8);
		$this->Cell(0,5,'Page '.$this->PageNo()." / {nb}",0,0,'C');
	}
}

$pdf = new PDF('P','mm','Letter');
$pdf->AliasNbPages();
$pdf->SetTitle("Success Internation School -Course Enrollment Details");
$pdf->AddPage();

$pdf->SetFont('Arial','',12);
$pdf->SetFillColor(230,230,230);
$pdf->Cell(15 ,15, $pdf->Image('assets/images/sis-logo-md.png', 10, 9.5, 16, 16), 0, 0, 'C', false);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(115 ,15,' SUCCESS INTERNATIONAL SCHOOL',0,0);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(15,15,'Report: ',0,0);
$pdf->Cell(50,15,'Exam Report',0,1);

$pdf->Cell(195 ,5,'',0,1);

$pdf->SetFont('Arial','',10);
$pdf->Cell(30 ,5,'Head Office        :',0,0);
$pdf->Cell(100 ,5,'No 13/B, Colombo Road,',0,0);
$pdf->Cell(15 ,5,'Tel      :',0,0);
$pdf->Cell(50 ,5,'011-2345678',0,1);

$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(100 ,5,'Wattala.',0,0);
$pdf->Cell(15 ,5,'Email  :',0,0);
$pdf->Cell(50 ,5,'info@sis.edu',0,1);

$pdf->Cell(195 ,5,'',0,1);

$pdf->Cell(30 ,5,'Generated By     :',0,0);
$pdf->Cell(35, 5, $session->get_session('fname') . ' ' . $session->get_session('lname') . ' (' . $session->get_session('userid') . ')', 0, 0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,1);

$pdf->Cell(0 ,15,'__________________________________________________________________________________________________',0,1);

$pdf->SetFont('Arial','B',9);
$pdf->Cell(10, 5,'#',0,0);
$pdf->Cell(15, 5,'ID',0,0);
$pdf->Cell(80, 5,'Exam Name',0,0);
$pdf->Cell(25, 5,'Date',0,0);
$pdf->Cell(25, 5,'Start Time',0,0);
$pdf->Cell(30, 5,'End Time',0,0);
$pdf->Cell(30, 5,'fee',0,1);

$exam_count = 1;

$result = $dbconn->query("select * from exams");
while($row = $result->fetch_assoc()){

	$pdf->SetFont('Arial','',9);
	$pdf->Cell(10, 5, $exam_count++, 0, 0);
	$pdf->Cell(15, 5, $row['id'], 0, 0);
	$pdf->Cell(80, 5, $row['name'], 0, 0);
	$pdf->Cell(25, 5, $row['date'], 0, 0);
	$pdf->Cell(25, 5, $row['time_start'], 0, 0);
	$pdf->Cell(30, 5, $row['time_end'], 0, 0);
	$pdf->Cell(30, 5, $row['fee'], 0, 1);
//	$pdf->Cell(30, 5, ();

}

$pdf->Close();
$pdf->Output();

?>
