<?php
include_once 'common_functions.php';
include_once 'ClassStaff.php';
$session = new SessionManager();
include_once 'assets/fpdf/fpdf.php';
include_once "DB_Connection.php";

class PDF extends FPDF {
	function Footer(){
		$this->SetY(-15);
		$this->SetFont('Arial','',7);
		$this->Cell(0 ,5,'Note : This is a computer generated sheet, no signature is required.',1,1,'C');
		$this->SetFont('Arial','',8);
		$this->Cell(0,5,'Page '.$this->PageNo()." / {nb}",0,0,'C');
	}
var $angle=0;

function Rotate($angle,$x=-1,$y=-1)
{
    if($x==-1)
        $x=$this->x;
    if($y==-1)
        $y=$this->y;
    if($this->angle!=0)
        $this->_out('Q');
    $this->angle=$angle;
    if($angle!=0)
    {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.5F %.5F %.5F %.5F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
    }
}

function _endpage()
{
    if($this->angle!=0)
    {
        $this->angle=0;
        $this->_out('Q');
    }
    parent::_endpage();
}
function Header()
{
    //Put the watermark
    $this->SetFont('Arial','B',50);
    $this->SetTextColor(218, 225, 221);
    $this->RotatedText(20,250,'Success International School',45);
}

function RotatedText($x, $y, $txt, $angle)
{
    //Text rotated around its origin
    $this->Rotate($angle,$x,$y);
    $this->Text($x,$y,$txt);
    $this->Rotate(0);
}
}
if(isset($_POST["report"])){
	$status = $_POST["pay_method"];	
	if($status == "All"){
		$sql = "select * from incomes";
	}else{
		$sql = "select * from incomes where payment_method = '$status'";
	}
		
		$result = $conn->query($sql);
if($result->num_rows == 0){
			set_error_msg("<strong>Oops!</strong> No ".$status." Incomes available!...");
			header("Location: Finance_Income_Report.php");
}
$pdf = new PDF('P','mm','Letter');
$pdf->AliasNbPages();
$pdf->SetTitle("Success Internation School - ".ucfirst($status)." Income History");
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$pdf->SetFillColor(230,230,230);
$pdf->Cell(15 ,15,'SIS',1,0,'C', TRUE);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(115 ,15,' SUCCESS INTERNATIONAL SCHOOL',0,0);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(15,15,'Report: ',0,0);
$pdf->Cell(100,15,ucfirst($status).' Incomes',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(30 ,5,'Head Office        :',0,0);
$pdf->Cell(100 ,5,'No 13/B, Colombo Road,',0,0);
$pdf->Cell(15 ,5,'Tel      :',0,0);
$pdf->Cell(50 ,5,'011-2345678',0,1);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(100 ,5,'Wattala.',0,0);
$pdf->Cell(15 ,5,'Email  :',0,0);
$pdf->Cell(50 ,5,'info@sis.edu',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->Cell(30 ,5,'Generated By     :',0,0);
$pdf->Cell(35, 5, $session->get_session('fname') . ' ' . $session->get_session('lname') . ' (' . $session->get_session('userid') . ')', 0, 0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,1);
$pdf->Cell(0 ,15,'__________________________________________________________________________________________________',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(5, 5,'#',0,0);
$pdf->Cell(35, 5,'Catogory',0,0);
$pdf->Cell(75, 5,'Description',0,0);
$pdf->Cell(30, 5,'Payment Method',0,0);
$pdf->Cell(20, 5,'Amount',0,0);
$pdf->Cell(20, 5,'Paid For',0,0);
$pdf->Cell(30, 5,'Status',0,1);
$i = 1;
$tot = 0;
while($row = $result->fetch_assoc()){

	$pdf->SetFont('Arial','',9);
	$pdf->Cell(5, 5, $i, 0, 0);
	$pdf->Cell(35, 5, $row["catogory"], 0, 0);
	$pdf->Cell(75, 5, $row["description"], 0, 0);
	$pdf->Cell(30, 5, $row["payment_method"], 0, 0);
	$pdf->Cell(20, 5, number_format((float)$row["amount"], 2, '.', ''), 0, 0);
	$pdf->Cell(20, 5, $row["paid_by"], 0, 0);
	$pdf->Cell(30, 5, $row["status"], 0, 1);
	$tot = $tot + $row["amount"];
	$i++;
}
$pdf->Cell(0 ,15,'________________________________________________________________________________________________________________',0,1);
$pdf->SetFont('Arial','B',9);
	$pdf->Cell(5, 5,"", 0, 0);
	$pdf->Cell(35, 5,"Total Incomes ", 0, 0);
	$pdf->Cell(75, 5, "", 0, 0);
	$pdf->Cell(30, 5, "", 0, 0);
	$pdf->Cell(20, 5, number_format((float)$tot, 2, '.', ''), 0, 0);
	$pdf->Cell(20, 5, "", 0, 0);
	$pdf->Cell(30, 5, "", 0, 1);
$pdf->Close();
$pdf->Output();
}
?>