<?php
include_once 'common_functions.php';
include_once 'ClassStaff.php';
$session = new SessionManager();
include_once 'assets/fpdf/fpdf.php';
include_once "DB_Connection.php";

class PDF extends FPDF {
	function Footer(){
		$this->SetY(-15);
		$this->SetFont('Arial','',7);
		$this->Cell(0 ,5,'Note : This is a computer generated sheet, no signature is required.',1,1,'C');
		$this->SetFont('Arial','',8);
		$this->Cell(0,5,'Page '.$this->PageNo()." / {nb}",0,0,'C');
	}
var $angle=0;

function Rotate($angle,$x=-1,$y=-1)
{
    if($x==-1)
        $x=$this->x;
    if($y==-1)
        $y=$this->y;
    if($this->angle!=0)
        $this->_out('Q');
    $this->angle=$angle;
    if($angle!=0)
    {
        $angle*=M_PI/180;
        $c=cos($angle);
        $s=sin($angle);
        $cx=$x*$this->k;
        $cy=($this->h-$y)*$this->k;
        $this->_out(sprintf('q %.5F %.5F %.5F %.5F %.2F %.2F cm 1 0 0 1 %.2F %.2F cm',$c,$s,-$s,$c,$cx,$cy,-$cx,-$cy));
    }
}

function _endpage()
{
    if($this->angle!=0)
    {
        $this->angle=0;
        $this->_out('Q');
    }
    parent::_endpage();
}
function Header()
{
    //Put the watermark
    $this->SetFont('Arial','B',50);
    $this->SetTextColor(218, 225, 221);
    $this->RotatedText(20,250,'Success International School',45);
}

function RotatedText($x, $y, $txt, $angle)
{
    //Text rotated around its origin
    $this->Rotate($angle,$x,$y);
    $this->Text($x,$y,$txt);
    $this->Rotate(0);
}
}
if(isset($_POST["report"])){
		$sql = "select * from payroll";
		$result = $conn->query($sql);
if($result->num_rows == 0){
			set_error_msg("<strong>Oops!</strong> No Payrolls available!...");
			header("Location: Finance_Payroll_Report.php");
}
$pdf = new PDF('P','mm','Letter');
$pdf->AliasNbPages();
$pdf->SetTitle("Success Internation School - Payroll Company Expenses");
$pdf->AddPage();
$pdf->SetFont('Arial','',12);
$pdf->SetFillColor(230,230,230);
$pdf->Cell(15 ,15,'SIS',1,0,'C', TRUE);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(115 ,15,' SUCCESS INTERNATIONAL SCHOOL',0,0);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(15,15,'Report: ',0,0);
$pdf->Cell(100,15,'Payroll Company Expenses',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->SetFont('Arial','',10);
$pdf->Cell(30 ,5,'Head Office        :',0,0);
$pdf->Cell(100 ,5,'No 13/B, Colombo Road,',0,0);
$pdf->Cell(15 ,5,'Tel      :',0,0);
$pdf->Cell(50 ,5,'011-2345678',0,1);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(100 ,5,'Wattala.',0,0);
$pdf->Cell(15 ,5,'Email  :',0,0);
$pdf->Cell(50 ,5,'info@sis.edu',0,1);
$pdf->Cell(195 ,5,'',0,1);
$pdf->Cell(30 ,5,'Generated By     :',0,0);
$pdf->Cell(35, 5, $session->get_session('fname') . ' ' . $session->get_session('lname') . ' (' . $session->get_session('userid') . ')', 0, 0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,1);
$pdf->Cell(0 ,15,'__________________________________________________________________________________________________',0,1);
$pdf->SetFont('Arial','B',9);
$pdf->Cell(5, 5,'#',0,0);
$pdf->Cell(25, 5,'Staff ID',0,0);
$pdf->Cell(25, 5,'Month',0,0);
$pdf->Cell(15, 5,'Year',0,0);
$pdf->Cell(30, 5,'Employer EPF',0,0);
$pdf->Cell(30, 5,'Employer ETF',0,0);
$pdf->Cell(30, 5,'Allowance',0,0);
$pdf->Cell(20, 5,'Net Salary',0,0);
$pdf->Cell(20, 5,'Status',0,1);
$i = 1;
$tot1 = 0;
$tot2 = 0;
$tot3 = 0;
$tot4 = 0;
while($row = $result->fetch_assoc()){

	$pdf->SetFont('Arial','',9);
	$pdf->Cell(5, 5, $i, 0, 0);
	$pdf->Cell(25, 5, $row["staff_id"], 0, 0);
	$pdf->Cell(25, 5, $row["month"], 0, 0);
	$pdf->Cell(15, 5, $row["year"], 0, 0);
	$pdf->Cell(30, 5, number_format((float)$row["employer_epf"], 2, '.', ''), 0, 0);
	$pdf->Cell(30, 5, number_format((float)$row["employer_etf"], 2, '.', ''), 0, 0);
	$pdf->Cell(30, 5, number_format((float)$row["allowance"], 2, '.', ''), 0, 0);
	$pdf->Cell(20, 5, number_format((float)$row["net_sal"], 2, '.', ''), 0, 0);
	$pdf->Cell(30, 5, $row["status"], 0, 1);
	$tot1 = $tot1 + $row["employer_epf"];
	$tot2 = $tot2 + $row["employer_etf"];
	$tot3 = $tot3 + $row["allowance"];
	$tot4 = $tot4 + $row["net_sal"];
	$i++;
}
$pdf->Cell(0 ,15,'______________________________________________________________________________________________________________',0,1);
$pdf->SetFont('Arial','B',9);
	$pdf->Cell(5, 5,"", 0, 0);
	$pdf->Cell(25, 5,"Total Payrolls ", 0, 0);
	$pdf->Cell(25, 5, "", 0, 0);
	$pdf->Cell(15, 5, "", 0, 0);
	$pdf->Cell(30, 5, number_format((float)$tot1, 2, '.', ''), 0, 0);
	$pdf->Cell(30, 5, number_format((float)$tot2, 2, '.', ''), 0, 0);
	$pdf->Cell(30, 5, number_format((float)$tot3, 2, '.', ''), 0, 0);
	$pdf->Cell(20, 5, number_format((float)$tot4, 2, '.', ''), 0, 0);
	$pdf->Cell(20, 5, "", 0, 0);
	$pdf->Cell(30, 5, "", 0, 1);
$pdf->Close();
$pdf->Output();

}
?>