<?php
include_once 'common_functions.php';
include_once 'ClassStaff.php';
$session = new SessionManager();
$staff_manager = new StaffManager();
$employees = $staff_manager->get_employee_list_with_departments();

include_once 'assets/libs/fpdf181/fpdf.php';

class PDF extends FPDF {
	function Footer(){
		$this->SetY(-15);
		$this->SetFont('Arial','',7);
		$this->Cell(0 ,5,'Note : This is a computer generated sheet, no signature is required.',1,1,'C');
		$this->SetFont('Arial','',8);
		$this->Cell(0,5,'Page '.$this->PageNo()." / {nb}",0,0,'C');
	}
}

$pdf = new PDF('P','mm','Letter');
$pdf->AliasNbPages();
$pdf->SetTitle("Success Internation School - Employment History Report");
$pdf->AddPage();

$pdf->SetFont('Arial','',12);
$pdf->SetFillColor(230,230,230);
$pdf->Cell(15 ,15, $pdf->Image('assets/images/sis-logo-md.png', 10, 9.5, 16, 16), 0, 0, 'C', false);
$pdf->SetFont('Arial','B',14);
$pdf->Cell(115 ,15,' SUCCESS INTERNATIONAL SCHOOL',0,0);
$pdf->SetFont('Arial','B',10);
$pdf->Cell(15,15,'Report: ',0,0);
$pdf->Cell(50,15,'Employment History',0,1);

$pdf->Cell(195 ,5,'',0,1);

$pdf->SetFont('Arial','',10);
$pdf->Cell(30 ,5,'Head Office        :',0,0);
$pdf->Cell(100 ,5,'No 13/B, Colombo Road,',0,0);
$pdf->Cell(15 ,5,'Tel      :',0,0);
$pdf->Cell(50 ,5,'011-2345678',0,1);

$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(100 ,5,'Wattala.',0,0);
$pdf->Cell(15 ,5,'Email  :',0,0);
$pdf->Cell(50 ,5,'info@sis.edu',0,1);

$pdf->Cell(195 ,5,'',0,1);

$pdf->Cell(30 ,5,'Generated By     :',0,0);
$pdf->Cell(35, 5, $session->get_session('fname') . ' ' . $session->get_session('lname') . ' (' . $session->get_session('userid') . ')', 0, 0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,0);
$pdf->Cell(30 ,5,'',0,0);
$pdf->Cell(35 ,5,'',0,1);

$pdf->Cell(0 ,15,'__________________________________________________________________________________________________',0,1);

$pdf->SetFont('Arial','B',9);
$pdf->Cell(10, 5,'#',0,0);
$pdf->Cell(30, 5,'Employee ID',0,0);
$pdf->Cell(35, 5,'First Name',0,0);
$pdf->Cell(35, 5,'Last Name',0,0);
$pdf->Cell(35, 5,'Recruited Date',0,0);
$pdf->Cell(50, 5,'Department',0,1);

$emp_count = 1;
foreach ($employees as $employee) {
	$pdf->SetFont('Arial','',9);
	$pdf->Cell(10, 5, $emp_count++, 0, 0);
	$pdf->Cell(30, 5, $employee['userid'], 0, 0);
	$pdf->Cell(35, 5, $employee['fname'], 0, 0);
	$pdf->Cell(35, 5, $employee['lname'], 0, 0);
	$pdf->Cell(35, 5, substr($employee['reg_date'], 0, 10), 0, 0);
	$pdf->Cell(50, 5, (strlen($employee['department'])) ? $employee['department'] : '- - -', 0, 1);
}

$pdf->Close();
$pdf->Output();

?>
